[HACK]fetch-wireguard: Comment out certain functions
Commenting out certain functions to avoid re-definitions just because
of few backports and this spits out an error.

In file included from <command-line>:
./../net/wireguard/compat/compat.h:347:20: error: static declaration of 'rng_is_initialized' follows non-static declaration
  347 | static inline bool rng_is_initialized(void)
      |                    ^~~~~~~~~~~~~~~~~~
In file included from ./../net/wireguard/compat/compat.h:335,
                 from <command-line>:
../include/linux/random.h:44:13: note: previous declaration of 'rng_is_initialized' was here
   44 | extern bool rng_is_initialized(void);
      |             ^~~~~~~~~~~~~~~~~~
make[3]: *** [../scripts/Makefile.build:361: net/wireguard/main.o] Error 1

Change-Id: Ib096ede5480d2d9e10f5f694f9eac8c692ed9e2a
Signed-off-by: Panchajanya1999 <panchajanya@azure-dev.live>